name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches:
      - main
      - Dev

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compilar con Maven
        run: mvn clean install --batch-mode --no-transfer-progress
        id: build_push
      - name: Checkear build de Maven
        run: |
          if [ $? -ne 0 ]; then
            echo "Fallo en el build."
            echo "::set-output name=build_status::failed"
          else
            echo "::set-output name=build_status::success"
          fi
      - name: Agregar comentario de error al PR
        uses: actions/github-script@v4
        if: ${{ github.event.action }} == 'pull_request' && ${{ needs.build_pull_request.outputs.build_status == 'failed' }}
        with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const comment = `El build falló. Por favor, revisar el log de la acción.`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          })
        run: echo "Error en el PR!"
      - name: Funcionó todo!
        if: ${{ needs.build_pull_request.outputs.build_status == 'success' }}
        run: echo "Felicitaciones a quien haya pusheado esto!"


#  build_pull_request:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#      - name: Compilar con Maven (pull request)
#        run: mvn clean install --batch-mode --no-transfer-progress
#        id: build_pull_request
#      - name: Checkear build de Maven (pull request)
#        run: |
#          if [ $? -ne 0 ]; then
#            echo "Fallo en el build."
#            echo "::set-output name=build_status::failed"
#          else
#            echo "::set-output name=build_status::success"
#          fi
#      - name: Agregar comentario de error al PR
#        uses: actions/github-script@v4
#        if: ${{ needs.build_pull_request.outputs.build_status == 'failed' }}
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const comment = `El build falló. Por favor, revisar el log de la acción.`;
#            github.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: comment
#            })
#      - name: Funcionó todo! (pull request)
#        run: echo "Felicitaciones a quien haya pusheado esto!"
