name: Java con Maven push

on:
  pull_request:
    branches:
      - main
      - Dev
w
jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      issues: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compilar con Maven
        run: mvn clean install --batch-mode --no-transfer-progress
        id: build_push
      - name: Agregar comentario de error al PR
        uses: actions/github-script@v4
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `El build falló. Por favor, revisar el log de la acción.`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
