name: Java con Maven push

on:
  push:
    branches: [ "*" ]

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compilar con Maven
        run: mvn clean install --batch-mode --no-transfer-progress
        id: build_push
      - name: Funcionó todo!
        if: success()
        run: echo "Felicitaciones a quien haya creado esto!"